@RiverBooks.Web_HostAddress = https://localhost:7240

GET {{RiverBooks.Web_HostAddress}}/books
Accept: application/json

### 
@BookID=0203517e-dc92-42c3-b6d5-267adec4faec
GET {{RiverBooks.Web_HostAddress}}/books/{{BookId}}
Accept:application/json

###
POST {{RiverBooks.Web_HostAddress}}/books
Accept:application/json
Content-Type: application/json
{
	"id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
	"title": "Livro de testes",
	"author": "Teste da Silva",
	"price": 20.27
}

###
# Testa o location header
GET {{RiverBooks.Web_HostAddress}}/books/3fa85f64-5717-4562-b3fc-2c963f66afa6
Accept:application/json

###
DELETE {{RiverBooks.Web_HostAddress}}/books/3fa85f64-5717-4562-b3fc-2c963f66afa6
Accept:application/json

###
POST {{RiverBooks.Web_HostAddress}}/books/3fa85f64-5717-4562-b3fc-2c963f66afa6/pricehistory
Accept:application/json
Content-Type: application/json
{
	"id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
	"price": 9.99
}

###
POST {{RiverBooks.Web_HostAddress}}/users
Accept: application/json
Content-Type: application/json
{
	"email":"steve@test.com",
	"password":"Pass@word1"
}
###

POST {{RiverBooks.Web_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json
{
	"email":"steve@test.com",
	"password":"Pass@word1"
}
###
@token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJzdGV2ZUB0ZXN0LmNvbSIsImlhdCI6MTcyNzYzMTkxMywiZXhwIjoxNzI3NjM1NTEzLCJuYmYiOjE3Mjc2MzE5MTN9.K5cyhqItuY6EQBlZfWZqXUGFcR3--1AmW7-4Txon80w



