// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RiverBooks.Books.Data.Migrations
{
	[DbContext(typeof(BookDbContext))]
    [Migration("20240915185948_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Books")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RiverBooks.Books.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books", "Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e47a0547-ff77-488f-9d2d-cf4ad659cf37"),
                            Author = "J.R.R. Tolkien",
                            Price = 10.99m,
                            Title = "A Sociedade do Anel"
                        },
                        new
                        {
                            Id = new Guid("79329a9f-fac7-4f86-8224-e4e3792f0ce6"),
                            Author = "J.R.R. Tolkien",
                            Price = 14.99m,
                            Title = "As Duas Torres"
                        },
                        new
                        {
                            Id = new Guid("0203517e-dc92-42c3-b6d5-267adec4faec"),
                            Author = "J.R.R. Tolkien",
                            Price = 19.99m,
                            Title = "O Retorno do Rei"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
